version: '3.8'

services:
  web:
    build: .
    container_name: geodjango_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    container_name: geodjango_db
    restart: always
    environment:
      POSTGRES_DB: geodjango
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: